# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.higherhangers.com
title: Higher Hangers - Space Saving Velvet Plastic & Wood Clothes Hangers
email: your-email@domain.com
author: Drew Cleaver
#description: see head.html
copyright: 'Copyright &copy; 2017 Higher Hangers. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>'
baseurl: "/hh"
fb-img: plain-hanger.jpg
nav-logo: nav_logo.png
mobile-nav-logo: nav_logo_mobile.png
baseurl: ""

#Live Website
#

#Localhost
#destination:  /Users/Matt/Dropbox/01 higherhangers shared/_site

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none #pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 

opt-in-text: Yes! I Want Higher Hangers
get-text: Buy Higher Hangers
get-url: http://shop.higherhangers.com
#get-url: https://shop.higherhangers.com?utm_source=higherhangers.com&utm_medium=link&utm_campaign=preorder
#get-url: https://www.kickstarter.com/projects/higherhangers/higher-hangers-space-saving-closet-organization-re?utm_source=higherhangers.com&utm_medium=link&utm_campaign=kspledges
#get-url: https://shop.trycelery.com/page/1ad1c157-3e14-4591-b7d5-ea2c556300fb
alert: true #UNCOMMENT BODY MARGIN AT BOTTOM OF CSS WHEN ACTIVE
kickstarter-url: http://kickstarter.com

collections:
  - text_files
  - perfect_for
  - faq
  - social
  
exclude: [_old_files]